package Bako;

import java.time.LocalDate;

public class BasicMember extends BonusMember implements IRegister {
    /**
     * @param memberNo     memberNo a unique number of a user generated by Random class
     * @param personals    personal information of a user, like name, e-mail address
     * @param enrolledDate the date that user enrolled
     *                     bonusPoints earned points
     */


    public BasicMember(int memberNo, Personals personals, LocalDate enrolledDate,int sumPoint,int bonusPoint) {
        super(memberNo, personals, enrolledDate,sumPoint,bonusPoint);

    }
public BasicMember(){}
    @Override
    public int registerPoint(int memberNO, int bonusPoint) {
        return bonusPoint;
    }



    @Override
    public String toString() {
        return
                "|"+getMemberNo()+ "   |"+getPersonals().getSurname() +" \t\t|"+ getBonusPoints() +"\t\t|"+"Basic Member"+"\t\t|"+
                getSumPoint()+"\t\t\t|\t"+getEnrolledDate()+"\t\t|";
    }

}
