package Bako;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

/**
 * The BonusMember-class holds  information like memberNumber,personalInfo,and enrolledDate
 * like: surname, lastnam, e-mail address and password.
 * The class is the Basic class for
 *
 * */
public class BonusMember implements IRegister {
    private  int memberNo;
    private  Personals personals;
    private  LocalDate enrolledDate;
    private int sumPoint;
    private int bonusPoints;

    /**
     * @param memberNo memberNo a unique number of a user generated by Random class
     * @param personals personal information of a user, like name, e-mail address
     * @param enrolledDate the date that user enrolled
     * bonusPoints earned points
     * */

    public BonusMember(int memberNo,Personals personals,LocalDate enrolledDate, int sumPoint,int bonusPoints) {
        this.memberNo = memberNo;
        this.personals=personals;
        this.enrolledDate=enrolledDate;
        this.sumPoint += sumPoint;
        this.bonusPoints = bonusPoints;

    }
public BonusMember(){}


    /**
     * @return memberNo return the member number of a user
     *
     * */

    public int getMemberNo() {
        return memberNo;
    }
    /**
     * @return personals returns the personals
     * */
    public Personals getPersonals() {
        return personals;
    }

    /**
     * @return enrolledDte returnsEnrolled date in the form fo yyyy-mm-dd
     *
     *
     */
    public LocalDate getEnrolledDate() {
        return enrolledDate;
    }
    /**
     * @return returns bonusPoints
     *
     * */
    public int getBonusPoints() {
        return bonusPoints;
    }

    /**
     * @param password user password
     * @return return true if password exist false otherwise
     * */
    public boolean okPassword(String password){
        return personals.okPassword(password);
    }
    /**
     //* @param bonusPoints bonus points to register
     * adds newly earned point to the earlier bonusPoints if any
     * */


  /*  public void setSumPoint(int memberNo,int sumPoint){
        if(memberNo==this.memberNo){
        this.sumPoint += sumPoint;
       }*/
public int getSumPoint(){return sumPoint;}


    @Override
    public int registerPoint(int memberNO, int bonusPoint) {
        return 0;
    }
}

